language: node_js
node_js:
  - "0.12"
addons:
  sauce_connect:
    username: "huangjian-storage"
    access_key: "a8e53e67-4c1b-4568-bb86-849bccdf0b13"
before_install:
  - "npm run-script prepare-test"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: "npm run-script test-travis"
after_script: "npm run-script test-saucelab"
after_success: "npm install coveralls@2.10.0 && cat ./coverage/lcov.info | coveralls"